backendBundle\Entity\Usuario:
    type: entity
    table: usuarios
    id:
        usuarioId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: usuario_id
            generator:
                strategy: IDENTITY
    fields:
        usuario:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        credencial:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        email:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        apellidos:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        nombres:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        foto:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        fNacimiento:
            type: date
            nullable: true
            column: f_nacimiento
        role:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
        estado:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
        creado:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
    lifecycleCallbacks: {  }
